# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='authentification.proto',
  package='grpc.auth',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x61uthentification.proto\x12\tgrpc.auth\"\x1b\n\x07Request\x12\x10\n\x08username\x18\x03 \x01(\t\"\x1d\n\x08Response\x12\x11\n\tisSuccess\x18\x02 \x01(\x08\x32@\n\x0b\x41uthService\x12\x31\n\x06SignIn\x12\x12.grpc.auth.Request\x1a\x13.grpc.auth.Responseb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc.auth.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='grpc.auth.Request.username', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=64,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='grpc.auth.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='grpc.auth.Response.isSuccess', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'authentification_pb2'
  # @@protoc_insertion_point(class_scope:grpc.auth.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'authentification_pb2'
  # @@protoc_insertion_point(class_scope:grpc.auth.Response)
  ))
_sym_db.RegisterMessage(Response)



_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='AuthService',
  full_name='grpc.auth.AuthService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=97,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='grpc.auth.AuthService.SignIn',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['AuthService'] = _AUTHSERVICE

# @@protoc_insertion_point(module_scope)
